accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

forum/urls.py
from django.contrib import admin
from django.urls import path,include
from forum_app.views import *
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('forum_app/', include('forum_app.urls'),name='forum_app'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),

]

forum_app/urls.py
from django.contrib import admin
from django.urls import path
from forum_app.views import *

urlpatterns = [
    path('',home,name='home'),
    path('addInForum/',addInForum,name='addInForum'),
    path('addInDiscussion/',addInDiscussion,name='addInDiscussion'),
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

forum_app/models.py
from django.db import models

# Create your models here.
class forum(models.Model):
    name=models.CharField(max_length=200,default="anonymous" )
    email=models.CharField(max_length=200,null=True)
    topic= models.CharField(max_length=300)
    description = models.CharField(max_length=1000,blank=True)
    link = models.CharField(max_length=100 ,null =True)
    date_created=models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return str(self.topic)

#child model
class Discussion(models.Model):
    forum = models.ForeignKey(forum,blank=True,on_delete=models.CASCADE)
    discuss = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.forum)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

forum_app/forms.py
from django.forms import ModelForm
from .models import *


class CreateInForum(ModelForm):
    class Meta:
        model= forum
        fields = "__all__"

class CreateInDiscussion(ModelForm):
    class Meta:
        model= Discussion
        fields = "__all__"

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

forum/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

forum_app/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
# Create your views here.

app_name = 'forum_app'

def home(request):
    forums=forum.objects.all()
    count=forums.count()
    discussions=[]
    for i in forums:
        discussions.append(i.discussion_set.all())

    context={'forums':forums,
              'count':count,
              'discussions':discussions}
    return render(request,'home.html',context)

def addInForum(request):
    form = CreateInForum()
    if request.method == 'POST':
        form = CreateInForum(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context ={'form':form}
    return render(request,'forum.html',context)

def addInDiscussion(request):
    form = CreateInDiscussion()
    if request.method == 'POST':
        form = CreateInDiscussion(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context ={'form':form}
    return render(request,'discussion.html',context)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Log In</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Forum</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">



  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Forums</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'forum_app:addInForum' %}" class="btn btn-simple">Create Forum</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'forum_app:home' %}"class="btn btn-simple">Forums</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



        <canvas id="canvas"></canvas>



  </body>
</html>

templates/discussion.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="{% url 'forum_app:addInDiscussion' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="submit">
</form>

{% endblock %}

templates/forum.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<form action="{% url 'forum_app:addInForum' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="submit">

{% endblock %}

templates/home.html
{% extends "base.html" %}
    <style>
        .box{
            border: 4px solid black;
            margin: 0 auto;
        }
    </style>
</head>

  {% block content %}

        <h2 class="jumbotron">
            Currently active forums: {{count}}
            <form method="POST" action="{% url 'forum_app:addInForum' %}">
                {% csrf_token %}
            <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px;">Add more</button>
            </form>
        </h2>
            <div class="card-columns" style="padding: 10px; margin: 20px;"></div>


            {%for forum in forums %}

                <div class="card box container"><span class="border">

                    <br>
                    <h5 class="card-title">
                        <a href='{{forum.link}}'><h3>{{forum.topic}}</h3></a>
                        <div class="card-body container">
                                <p>{{forum.description}}</p>
                            </h5>
                            <hr>
                            <p> By: {{forum.name}}</p>
                            email- {{forum.email}}
                            <hr>
                            <h4>Views from other users</h4>
                            {%for discuss in discussions%}
                            {%for objs in discuss%}
                            {% if objs.forum == forum %}
                               {{objs.discuss}}
                               <br>
                            {% endif %}
                            {%endfor%}
                            {%endfor%}
                            <form method="POST" action="{% url 'forum_app:addInDiscussion' %}">
                                {% csrf_token %}
                            <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px;">Add more</button>
                            </form>
                        </div>
                </span></div>
            </div>
            <br>

            {%endfor%}


  {% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Welcome to Forums</h1>

{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}
  <h1>You are Logged In</h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}
  <h1>Thanks for visitong, come back soon</h1>
{% endblock %}